# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0
  cypress: cypress-io/cypress@1

executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node16.14.0-chrome99-ff97"

jobs:
  build_react_app:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - aws-s3/copy:
          from: build/
          to: s3://techscrumapp.com
          arguments: --recursive
  code_qa:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  simple_workflow:
    jobs:
      - cypress/install: 
          install-command: yarn install --frozen-lockfile
      - cypress/run:
          yarn: true
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          start: 'yarn start'
          parallel: true
          post-steps:
            - run: ls
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/screenshots
      - code_qa
      - build_react_app:
          requires:
            - code_qa
          filters:
            branches:
              only:
                - master
